import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Manrope,
  Urbanist,
  Poppins,
  Vollkorn_SC,
} from "next/font/google";
import "./globals.css";
import MobileBottomDock from "@/components/MobileBottomDock";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const vollkornSc = Vollkorn_SC({
  variable: "--font-vollkorn-sc",
  subsets: ["latin"],
  weight: ["400", "600", "700", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} ${urbanist.variable} ${poppins.variable} ${vollkornSc.variable} font-manrope antialiased`}
      >
        {children}
        <MobileBottomDock />
      </body>
    </html>
  );
}
